apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= projectName %>
spec:
  selector:
    matchLabels:
      app: <%= projectName %>
  replicas: 2
  template:
    metadata:
      labels:
        app: <%= projectName %>
    spec:
      containers:
      - name: <%= projectName %>
        image: <%= projectName %>:latest
        ports:
          - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 1
          timeoutSeconds: 1
          httpGet:
            port: 3000
            path: /health
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 5
          httpGet:
            path: /health
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: <%= projectName %>
  labels:
    app: <%= projectName %>
spec:
  selector:
    app: <%= projectName %>
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000